version: '3.4'

networks:
  default:
    driver: bridge
services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
    - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - default
    volumes:
      - ./app/:/app
      - ./kpop_music_videos.csv:/app/kpop_music_videos.csv
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
    - "5080:5000"
    env_file:
      - .env
    depends_on:
      - db

# Ajout du service Keycloak
  keycloak:
    image: sleighzy/keycloak
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - default
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
      - keycloak_log:/opt/jboss/keycloak/standalone/log

volumes:
  keycloak_data:
  keycloak_log: